//
// Created by wilyarti on 16/9/25.
//

#ifndef ESP32RADIOALARMCLOCK_CURRENT_SENSOR_FUNCTIONS_H
#define ESP32RADIOALARMCLOCK_CURRENT_SENSOR_FUNCTIONS_H
#pragma once

#endif //ESP32RADIOALARMCLOCK_CURRENT_SENSOR_FUNCTIONS_H